[package]
name = "jack/the-part-experience"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"

[server-dependencies]
profilestore = "lm-loleris/profilestore@1.0.3"